# Generated by Django 5.2.6 on 2025-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='imagenes_referencia',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
