# Generated by Django 5.2.5 on 2025-11-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_pedidos_imagenes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
