# Generated by Django 5.2.5 on 2025-11-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='imagen_ref1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/', verbose_name='Imagen de referencia 1'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='imagen_ref2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/', verbose_name='Imagen de referencia 2'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='imagen_ref3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/', verbose_name='Imagen de referencia 3'),
        ),
    ]
