# Generated by Django 5.2.6 on 2025-11-30 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_pedidos_imagen_ref1_pedidos_imagen_ref2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_final', models.ImageField(upload_to='galeria_trabajos/', verbose_name='Foto del Producto Terminado')),
                ('descripcion_publica', models.TextField(help_text='Breve descripción de lo que se hizo.', verbose_name='Descripción para la Galería')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('mostrar_publicamente', models.BooleanField(default=False, verbose_name='Mostrar en Web Pública')),
                ('pedido_referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibicion', to='mainApp.pedidos', verbose_name='Pedido de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], verbose_name='Puntuación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario del Cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('exhibicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='mainApp.exhibicion', verbose_name='Muestra Calificada')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones de Pedidos',
            },
        ),
    ]
